In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

# 1. Broadcasting

## a) Add a 1D array `[1, 2, 3]` to each row of a 2D array `[[10, 20, 30], [40, 50, 60]]`.
## Expected: [[11, 22, 33], [41, 52, 63]]

In [2]:
a = np.array([[10, 20, 30], [40, 50, 60]])
b = np.array([1, 2, 3])
result = a + b
result

array([[11, 22, 33],
       [41, 52, 63]])

## b) Multiply a 2D array `[[1, 2], [3, 4]]` by a 1D array `[10, 20]` column-wise.
## Expected: [[10, 20], [60, 80]]

In [3]:
aa = np.array([[1, 2], [3, 4]])
bb = np.array([10, 20])
resultt = aa * bb[:, np.newaxis]
resultt

array([[10, 20],
       [60, 80]])

# 2. Indexing and Slicing (High Dimensional Arrays)


In [5]:
arr = np.arange(1, 25).reshape(2, 3, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## a) Extract the second slice along axis 0

In [6]:
second_slice = arr[1]
second_slice

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

## b) Extract all rows and the last column for all slices

In [7]:
last_column = arr[:, :, -1]
last_column

array([[ 4,  8, 12],
       [16, 20, 24]])

## c) Reverse the order of slices along axis 0

In [8]:
reversed_slices = arr[::-1]
reversed_slices

array([[[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

## d) Set all even elements in the array to -1

In [9]:
arr_with_negatives = arr.copy()
arr_with_negatives[arr_with_negatives % 2 == 0] = -1
arr_with_negatives

array([[[ 1, -1,  3, -1],
        [ 5, -1,  7, -1],
        [ 9, -1, 11, -1]],

       [[13, -1, 15, -1],
        [17, -1, 19, -1],
        [21, -1, 23, -1]]])

# 3. np.repeat

## a) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where every odd element is repeated twice.
## Expected: [1, 1, 3, 3, 5, 5]

In [10]:
arrr = np.array([1, 2, 3, 4, 5, 6])
odd_elements = arr[arr % 2 == 1]
result = np.repeat(odd_elements, 2)
result

array([ 1,  1,  3,  3,  5,  5,  7,  7,  9,  9, 11, 11, 13, 13, 15, 15, 17,
       17, 19, 19, 21, 21, 23, 23])

## b) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where elements are repeated based on their value.
## For example, `1` is repeated once, `2` twice, etc.
## Expected: [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, ...]

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.repeat(arr, arr)
result

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6])

# 4. Normalizing

## a) Normalize a 1D array `arr = np.array([10, 20, 30])` to have values between 0 and 1.
## Expected: [0.0, 0.5, 1.0]

In [12]:
arr = np.array([10, 20, 30])
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
normalized_arr

array([0. , 0.5, 1. ])

# 5. Bonus Challenge

## a) Normalize a 1D array `arr = np.array([10, 20, 30])` to have values between 0 and 1.
## Expected: [0.0, 0.5, 1.0]

In [13]:
n = 3
i = np.arange(n).reshape(n, 1)  
j = np.arange(n)  
matrix = i * j
matrix

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

## b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.
## Expected: Diagonal elements replaced with 0.

In [14]:
matrix = np.random.randint(1, 10, (4, 4))  
np.fill_diagonal(matrix, 0)
matrix

array([[0, 6, 4, 7],
       [9, 0, 2, 8],
       [5, 7, 0, 4],
       [7, 3, 7, 0]])